## CHANGE this to the name of your plugin.
name: SlimefunShop

## CHANGE this to your username.
author: Derpling

## CHANGE this to a meaninful but short description of your plugin.
description: Adds a new machine to change various materials into other ones!

## CHANGE this to the path of the class that extends JavaPlugin.
main: me.derpling.slimefunshop.SlimefunShop

## This is required and marks Slimefun as a plugin dependency.
depend: [Slimefun]

## This value is automatically replaced by the version specified in your pom.xml file, do not change this.
version: ${project.version}

## This is the minimum minecraft version required to run your plugin.
api-version: 1.14
